
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClaimInfo.DataModel
{

using System;
    using System.Collections.Generic;
    
public partial class ClaimDiagnosisInfo
{

    public int SeqID { get; set; }

    public string ClaimId { get; set; }

    public string FileID { get; set; }

    public Nullable<int> TransactionID { get; set; }

    public string FileName { get; set; }

    public string FileDate { get; set; }

    public string OccurenceLoop { get; set; }

    public string SequenceId { get; set; }

    public string HI01 { get; set; }

    public string HI02 { get; set; }

    public string HI03 { get; set; }

    public string HI04 { get; set; }

    public string HI05 { get; set; }

    public string HI06 { get; set; }

    public string HI07 { get; set; }

    public string HI08 { get; set; }

    public string HI09 { get; set; }

    public string HI10 { get; set; }

    public string ExtraField1 { get; set; }

    public string ExtraField2 { get; set; }

    public string ExtraField3 { get; set; }

    public string ExtraField4 { get; set; }

}

}
