
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClaimInfo.DataModel
{

using System;
    using System.Collections.Generic;
    
public partial class Claims_ICD_CODE
{

    public int SeqId { get; set; }

    public string ICD_CODE { get; set; }

    public string Year { get; set; }

    public string ExtraField1 { get; set; }

}

}
