
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClaimInfo.DataModel
{

using System;
    using System.Collections.Generic;
    
public partial class Claims278
{

    public int TranID { get; set; }

    public string TranName { get; set; }

    public string TranDate { get; set; }

    public string TranStatus { get; set; }

    public string Submitter { get; set; }

    public string ErrorCode { get; set; }

}

}
