
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClaimInfo.DataModel
{

using System;
    using System.Collections.Generic;
    
public partial class ClaimAdjustmentServiceLine
{

    public int SeqID { get; set; }

    public string ClaimId { get; set; }

    public string FileID { get; set; }

    public Nullable<int> TransactionID { get; set; }

    public string FileName { get; set; }

    public string FileDate { get; set; }

    public string OccurenceLoop { get; set; }

    public string SequenceId { get; set; }

    public string CAS01 { get; set; }

    public string CAS02 { get; set; }

    public string CAS03 { get; set; }

    public string CAS04 { get; set; }

    public string CAS05 { get; set; }

    public string CAS06 { get; set; }

    public string CAS07 { get; set; }

    public string CAS08 { get; set; }

    public string CAS09 { get; set; }

    public string CAS10 { get; set; }

    public string CAS11 { get; set; }

    public string CAS12 { get; set; }

    public string CAS13 { get; set; }

    public string CAS14 { get; set; }

    public string CAS15 { get; set; }

    public string CAS16 { get; set; }

    public string CAS17 { get; set; }

    public string CAS18 { get; set; }

    public string CAS19 { get; set; }

    public string CAS20 { get; set; }

    public string ExtraField1 { get; set; }

    public string ExtraField2 { get; set; }

    public string ExtraField3 { get; set; }

    public string ExtraField4 { get; set; }

}

}
