
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClaimInfo.DataModel
{

using System;
    using System.Collections.Generic;
    
public partial class Eligibility276
{

    public int ID { get; set; }

    public string TypeofTransaction { get; set; }

    public string AvgResTime { get; set; }

    public Nullable<int> TotalNumOfReq { get; set; }

    public Nullable<int> Success { get; set; }

    public Nullable<int> Error { get; set; }

}

}
