
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClaimInfo.DataModel
{

using System;
    using System.Collections.Generic;
    
public partial class FileInTake835
{

    public int SeqID { get; set; }

    public string FileID { get; set; }

    public Nullable<int> TransactionID { get; set; }

    public string FileName { get; set; }

    public string FileDate { get; set; }

    public string BatchID { get; set; }

    public Nullable<long> TransmissionID { get; set; }

    public string TradingPartner { get; set; }

    public string InterchangeSenderID { get; set; }

    public string InterchangeControlNumber { get; set; }

    public string InterchangeDate { get; set; }

    public string InterchangeTime { get; set; }

    public string SubmitterID { get; set; }

    public string ReceiverName { get; set; }

    public string ReceiverID { get; set; }

    public string Destination { get; set; }

    public string ISA01 { get; set; }

    public string ISA02 { get; set; }

    public string ISA03 { get; set; }

    public string ISA04 { get; set; }

    public string ISA05 { get; set; }

    public string ISA06 { get; set; }

    public string ISA07 { get; set; }

    public string ISA08 { get; set; }

    public string ISA09 { get; set; }

    public string ISA10 { get; set; }

    public string ISA11 { get; set; }

    public string ISA12 { get; set; }

    public string ISA13 { get; set; }

    public string ISA14 { get; set; }

    public string ISA15 { get; set; }

    public string ISA16 { get; set; }

    public string GSA01 { get; set; }

    public string GSA02 { get; set; }

    public string GSA03 { get; set; }

    public string GSA04 { get; set; }

    public string GSA05 { get; set; }

    public string GSA06 { get; set; }

    public string GSA07 { get; set; }

    public string GSA08 { get; set; }

    public string ST01 { get; set; }

    public string ST02 { get; set; }

    public string ST03 { get; set; }

    public string BHT01 { get; set; }

    public string BHT02 { get; set; }

    public string BHT03 { get; set; }

    public string BHT04 { get; set; }

    public string BHT05 { get; set; }

    public string BHT06 { get; set; }

    public string Sumbitter_N101 { get; set; }

    public string Submitter_N102 { get; set; }

    public string Submitter_N103 { get; set; }

    public string Submitter_N104 { get; set; }

    public string Submitter_N301 { get; set; }

    public string Submitter_N302 { get; set; }

    public string Submitter_N401 { get; set; }

    public string Submitter_N402 { get; set; }

    public string Submitter_N403 { get; set; }

    public string Submitter_PER01 { get; set; }

    public string Submitter_PER02 { get; set; }

    public string Submitter_PER03 { get; set; }

    public string Submitter_PER04 { get; set; }

    public string Submitter_PER05 { get; set; }

    public string Submitter_PER06 { get; set; }

    public string Receiver_N101 { get; set; }

    public string Receiver_N102 { get; set; }

    public string Receiver_N103 { get; set; }

    public string Receiver_N104 { get; set; }

    public string Receiver_N105 { get; set; }

    public string Receiver_N301 { get; set; }

    public string Receiver_N302 { get; set; }

    public string Receiver_N401 { get; set; }

    public string Receiver_N402 { get; set; }

    public string Receiver_N403 { get; set; }

    public string Receiver_PER01 { get; set; }

    public string Receiver_PER02 { get; set; }

    public string Receiver_PER03 { get; set; }

    public string Receiver_PER04 { get; set; }

    public string Receiver_PER05 { get; set; }

    public string Receiver_PER06 { get; set; }

    public Nullable<int> ClaimCount { get; set; }

    public Nullable<System.Guid> ExternalCorrelationToken { get; set; }

    public string ExtraField1 { get; set; }

    public string ExtraField2 { get; set; }

    public string ExtraField3 { get; set; }

    public string ExtraField4 { get; set; }

    public string ExtraField5 { get; set; }

    public string ExtraField6 { get; set; }

    public string ExtraField7 { get; set; }

    public string ExtraField8 { get; set; }

    public string ExtraField9 { get; set; }

    public string CreatedBy { get; set; }

    public string CreateDateTime { get; set; }

    public string Created_Date { get; set; }

    public string FileStatus { get; set; }

    public string FileLevelErrors { get; set; }

    public string Field2 { get; set; }

    public string Field3 { get; set; }

    public string Field4 { get; set; }

    public string Field5 { get; set; }

    public string Field6 { get; set; }

    public Nullable<int> error_claimcount { get; set; }

}

}
