

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClaimInfo.DataModel
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class HiPaaS_website_offshoreEntities : DbContext
{
    public HiPaaS_website_offshoreEntities()
        : base("name=HiPaaS_website_offshoreEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<FileInTake> FileInTakes { get; set; }

    public virtual DbSet<Claim_Status> Claim_Status { get; set; }

    public virtual DbSet<ClaimAdjustmentServiceLine> ClaimAdjustmentServiceLines { get; set; }

    public virtual DbSet<ClaimDiagnosisInfo> ClaimDiagnosisInfoes { get; set; }

    public virtual DbSet<ClaimInformationREF> ClaimInformationREFs { get; set; }

    public virtual DbSet<Claims_ICD_CODE> Claims_ICD_CODE { get; set; }

    public virtual DbSet<NoteClaim837> NoteClaim837 { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<LCD_Covered_Original> LCD_Covered_Original { get; set; }

    public virtual DbSet<Eligibility276> Eligibility276 { get; set; }

    public virtual DbSet<Eligibilty270> Eligibilty270 { get; set; }

    public virtual DbSet<ErrorType> ErrorTypes { get; set; }

    public virtual DbSet<FileInTake835> FileInTake835 { get; set; }

    public virtual DbSet<IntakeClaimData835> IntakeClaimData835 { get; set; }

    public virtual DbSet<IntakeClaimLineData835> IntakeClaimLineData835 { get; set; }

    public virtual DbSet<Claims278> Claims278 { get; set; }

    public virtual DbSet<Eligibilty_DateWise> Eligibilty_DateWise { get; set; }

    public virtual DbSet<IntakeClaimData> IntakeClaimDatas { get; set; }

    public virtual DbSet<IntakeClaimLineData> IntakeClaimLineDatas { get; set; }

    public virtual DbSet<AspNetRole> AspNetRoles { get; set; }

    public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }

    public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }

    public virtual DbSet<MemberCoverageInfo_M1> MemberCoverageInfo_M1 { get; set; }

    public virtual DbSet<MemberInfo_M1> MemberInfo_M1 { get; set; }


    public virtual ObjectResult<SP_GetClaimAmount_Result> SP_GetClaimAmount()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetClaimAmount_Result>("SP_GetClaimAmount");
    }


    public virtual ObjectResult<SP_GetClaims_ICD_CODE_Result> SP_GetClaims_ICD_CODE()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetClaims_ICD_CODE_Result>("SP_GetClaims_ICD_CODE");
    }


    public virtual ObjectResult<SP_GetCompanion_Guide_Result> SP_GetCompanion_Guide()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetCompanion_Guide_Result>("SP_GetCompanion_Guide");
    }


    public virtual ObjectResult<SP_GetLCD_Covered_Original_Result> SP_GetLCD_Covered_Original()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetLCD_Covered_Original_Result>("SP_GetLCD_Covered_Original");
    }


    public virtual int SP_GetLCD_SmallFile()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_GetLCD_SmallFile");
    }


    public virtual ObjectResult<SP_GetPendingClaimError_Result> SP_GetPendingClaimError()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetPendingClaimError_Result>("SP_GetPendingClaimError");
    }


    public virtual ObjectResult<SP_GetRejectedClaimError_Result> SP_GetRejectedClaimError()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetRejectedClaimError_Result>("SP_GetRejectedClaimError");
    }


    public virtual ObjectResult<SP_SearchClaims_Result> SP_SearchClaims()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SearchClaims_Result>("SP_SearchClaims");
    }


    public virtual ObjectResult<SP_GetCompanion_Guide_270_Result> SP_GetCompanion_Guide_270()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetCompanion_Guide_270_Result>("SP_GetCompanion_Guide_270");
    }


    public virtual ObjectResult<Nullable<int>> SP_GetFileInTakeCount(string filedate)
    {

        var filedateParameter = filedate != null ?
            new ObjectParameter("filedate", filedate) :
            new ObjectParameter("filedate", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_GetFileInTakeCount", filedateParameter);
    }


    public virtual ObjectResult<Nullable<int>> SP_getTotalFileCount(string filedate)
    {

        var filedateParameter = filedate != null ?
            new ObjectParameter("filedate", filedate) :
            new ObjectParameter("filedate", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_getTotalFileCount", filedateParameter);
    }


    public virtual ObjectResult<Nullable<int>> SP_GetIntakeClaimDataCount(string filedate)
    {

        var filedateParameter = filedate != null ?
            new ObjectParameter("filedate", filedate) :
            new ObjectParameter("filedate", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_GetIntakeClaimDataCount", filedateParameter);
    }


    public virtual ObjectResult<Nullable<int>> SP_GetIntakeClaimDataErrorsCount(string filedate)
    {

        var filedateParameter = filedate != null ?
            new ObjectParameter("filedate", filedate) :
            new ObjectParameter("filedate", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_GetIntakeClaimDataErrorsCount", filedateParameter);
    }


    public virtual ObjectResult<Nullable<int>> SP_GetIntakeClaimDataVarifiedCount(string filedate)
    {

        var filedateParameter = filedate != null ?
            new ObjectParameter("filedate", filedate) :
            new ObjectParameter("filedate", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_GetIntakeClaimDataVarifiedCount", filedateParameter);
    }


    public virtual ObjectResult<SP_GetRejectedClaims_Result> SP_GetRejectedClaims(string filedate)
    {

        var filedateParameter = filedate != null ?
            new ObjectParameter("filedate", filedate) :
            new ObjectParameter("filedate", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetRejectedClaims_Result>("SP_GetRejectedClaims", filedateParameter);
    }


    public virtual ObjectResult<SP_GetClaimDailyAuditCount_Result> SP_GetClaimDailyAuditCount(string filedate)
    {

        var filedateParameter = filedate != null ?
            new ObjectParameter("filedate", filedate) :
            new ObjectParameter("filedate", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetClaimDailyAuditCount_Result>("SP_GetClaimDailyAuditCount", filedateParameter);
    }


    public virtual ObjectResult<SP_GetClaimDailyAudit_Result> SP_GetClaimDailyAudit(string filedate)
    {

        var filedateParameter = filedate != null ?
            new ObjectParameter("filedate", filedate) :
            new ObjectParameter("filedate", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetClaimDailyAudit_Result>("SP_GetClaimDailyAudit", filedateParameter);
    }


    public virtual ObjectResult<Nullable<int>> SP_GetFileInTake835Count(string filedate)
    {

        var filedateParameter = filedate != null ?
            new ObjectParameter("filedate", filedate) :
            new ObjectParameter("filedate", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SP_GetFileInTake835Count", filedateParameter);
    }


    public virtual ObjectResult<SP_GetData_Wise270_Result> SP_GetData_Wise270(string sDate)
    {

        var sDateParameter = sDate != null ?
            new ObjectParameter("SDate", sDate) :
            new ObjectParameter("SDate", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetData_Wise270_Result>("SP_GetData_Wise270", sDateParameter);
    }


    public virtual ObjectResult<SP_GetDetails270_Result> SP_GetDetails270(string sDate, string type_ID)
    {

        var sDateParameter = sDate != null ?
            new ObjectParameter("SDate", sDate) :
            new ObjectParameter("SDate", typeof(string));


        var type_IDParameter = type_ID != null ?
            new ObjectParameter("Type_ID", type_ID) :
            new ObjectParameter("Type_ID", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetDetails270_Result>("SP_GetDetails270", sDateParameter, type_IDParameter);
    }


    public virtual ObjectResult<SP_GetLCD_SmallFileNew_Result> SP_GetLCD_SmallFileNew()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetLCD_SmallFileNew_Result>("SP_GetLCD_SmallFileNew");
    }


    public virtual ObjectResult<SP_LoginUserDetails_Result> SP_LoginUserDetails(string loginEmailID)
    {

        var loginEmailIDParameter = loginEmailID != null ?
            new ObjectParameter("LoginEmailID", loginEmailID) :
            new ObjectParameter("LoginEmailID", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LoginUserDetails_Result>("SP_LoginUserDetails", loginEmailIDParameter);
    }


    public virtual ObjectResult<SP_GetenrollmentDetails834_Result> SP_GetenrollmentDetails834()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetenrollmentDetails834_Result>("SP_GetenrollmentDetails834");
    }


    public virtual ObjectResult<SP_834DailyDashboardCount_Result> SP_834DailyDashboardCount()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_834DailyDashboardCount_Result>("SP_834DailyDashboardCount");
    }


    public virtual ObjectResult<SP_834FileDetails_Result> SP_834FileDetails(string text)
    {

        var textParameter = text != null ?
            new ObjectParameter("text", text) :
            new ObjectParameter("text", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_834FileDetails_Result>("SP_834FileDetails", textParameter);
    }


    public virtual ObjectResult<SP_834Filecountwisedetails_Result> SP_834Filecountwisedetails(string text)
    {

        var textParameter = text != null ?
            new ObjectParameter("text", text) :
            new ObjectParameter("text", typeof(string));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_834Filecountwisedetails_Result>("SP_834Filecountwisedetails", textParameter);
    }


    public virtual ObjectResult<SP_Daily834headerData_Result> SP_Daily834headerData()
    {

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Daily834headerData_Result>("SP_Daily834headerData");
    }


    public virtual ObjectResult<SP_834FileHeaderDetails_Result> SP_834FileHeaderDetails(string fileId, string subscriber, Nullable<int> type)
    {

        var fileIdParameter = fileId != null ?
            new ObjectParameter("FileId", fileId) :
            new ObjectParameter("FileId", typeof(string));


        var subscriberParameter = subscriber != null ?
            new ObjectParameter("Subscriber", subscriber) :
            new ObjectParameter("Subscriber", typeof(string));


        var typeParameter = type.HasValue ?
            new ObjectParameter("type", type) :
            new ObjectParameter("type", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_834FileHeaderDetails_Result>("SP_834FileHeaderDetails", fileIdParameter, subscriberParameter, typeParameter);
    }

}

}

