
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClaimInfo.DataModel
{

using System;
    using System.Collections.Generic;
    
public partial class IntakeClaimData
{

    public int SeqID { get; set; }

    public string FileID { get; set; }

    public string TransactionID { get; set; }

    public string FileName { get; set; }

    public string FileDate { get; set; }

    public string BatchID { get; set; }

    public string TransmissionID { get; set; }

    public string ClaimExtNmbr { get; set; }

    public string ClaimID { get; set; }

    public string ClaimTMTrackingID { get; set; }

    public string PaytoPlanInfo { get; set; }

    public string Billing_Provider_ID { get; set; }

    public string SecondaryBilling_ID { get; set; }

    public string Subscriber_ID { get; set; }

    public string ExtSubscriber_ID { get; set; }

    public string Member_ID { get; set; }

    public string Member_Account_Number { get; set; }

    public string Member_Last_Name { get; set; }

    public string Member_First_Name { get; set; }

    public string MemberMI { get; set; }

    public string Member_DOB { get; set; }

    public string DiagnosisCodes { get; set; }

    public string Claim_Amount { get; set; }

    public string PatientPaid { get; set; }

    public string NetBalance { get; set; }

    public string Adjust { get; set; }

    public string InsuranceBalance { get; set; }

    public string VAN_Trace_Number { get; set; }

    public string COB_Claim_Number { get; set; }

    public string ClaimStatus { get; set; }

    public string ClaimCode { get; set; }

    public string OtherID { get; set; }

    public string ClaimSupplimentalInfo { get; set; }

    public string ContractInformation { get; set; }

    public string PatientDueAmmount { get; set; }

    public string ExternalCorrelationToken { get; set; }

    public string LineCount { get; set; }

    public string ExtraField1 { get; set; }

    public string ExtraField2 { get; set; }

    public string ExtraField3 { get; set; }

    public string ExtraField4 { get; set; }

    public string ExtraField5 { get; set; }

    public string ExtraField6 { get; set; }

    public string ExtraField7 { get; set; }

    public string ExtraField8 { get; set; }

    public string ExtraField9 { get; set; }

    public string CreatedBy { get; set; }

    public string CreateDateTime { get; set; }

    public Nullable<System.DateTime> Created_Date { get; set; }

    public string HL_ID_BillingProvider { get; set; }

    public string HL_Level_BillingProvider { get; set; }

    public string PRV_Billing01 { get; set; }

    public string PRV_Billing02 { get; set; }

    public string PRV_Billing03 { get; set; }

    public string NM101_BillingProviderId { get; set; }

    public string BillingProviderLastName { get; set; }

    public string BillingProviderFirstName { get; set; }

    public string NM108_BillingProvider { get; set; }

    public string NM109_BillingProvider { get; set; }

    public string BillingProviderAddress { get; set; }

    public string BillingProviderCity_State_Zip { get; set; }

    public string BillingProvider_TaxId { get; set; }

    public string BillingProvider_PER01 { get; set; }

    public string BillingProvider_PER02 { get; set; }

    public string BillingProvider_PER03 { get; set; }

    public string BillingProvider_PER04 { get; set; }

    public string NM101_PayToProvider { get; set; }

    public string PayToProviderLastName { get; set; }

    public string PayToProviderFirstName { get; set; }

    public string NM108_PayToProvider { get; set; }

    public string NM109_PayToProvider { get; set; }

    public string PayToProviderAddress { get; set; }

    public string PayToProviderCity_State_Zip { get; set; }

    public string PayToProvider_TaxId { get; set; }

    public string PayToProvider_PER01 { get; set; }

    public string PayToProvider_PER02 { get; set; }

    public string PayToProvider_PER03 { get; set; }

    public string PayToProvider_PER04 { get; set; }

    public string HL_ID_Subscriber { get; set; }

    public string HL_Level_Subscriber { get; set; }

    public string SBR01 { get; set; }

    public string SBR02 { get; set; }

    public string SBR03 { get; set; }

    public string SBR09 { get; set; }

    public string SubscriberLastName { get; set; }

    public string SubscriberFirstName { get; set; }

    public string SubscriberDOB { get; set; }

    public string NM108_Subscriber { get; set; }

    public string NM109_Subscriber { get; set; }

    public string SubscriberAddress { get; set; }

    public string SubscriberCity_State_Zip { get; set; }

    public string SubscriberSecondaryIdentification { get; set; }

    public string CasualityClaimNumber { get; set; }

    public string PayerLastName { get; set; }

    public string PayerFirstName { get; set; }

    public string NM108_Payer { get; set; }

    public string NM109_Payer { get; set; }

    public string PayerAddress { get; set; }

    public string PayerCity_State_Zip { get; set; }

    public string PayerSecondaryId { get; set; }

    public string BillingProviderSecondaryId { get; set; }

    public string HL_ID_Patient { get; set; }

    public string HL_Level_Patient { get; set; }

    public string PatientLastName { get; set; }

    public string PatientFirstName { get; set; }

    public string NM108_Patient { get; set; }

    public string NM109_Patient { get; set; }

    public string PatientAddress { get; set; }

    public string PatientCity_State_Zip { get; set; }

    public string PatientDOB { get; set; }

    public string CLM01 { get; set; }

    public string CLM02 { get; set; }

    public string CLM05_01 { get; set; }

    public string CLM05_02 { get; set; }

    public string CLM05_03 { get; set; }

    public string StatementBegin { get; set; }

    public string StatementEnd { get; set; }

    public string DischargeHour { get; set; }

    public string AdmissionDate { get; set; }

    public string RepricerReceivevDate { get; set; }

    public string ErrorCode { get; set; }

    public string ErrorDesc { get; set; }

    public string Field1 { get; set; }

    public string ClaimLevelErrors { get; set; }

    public string Field3 { get; set; }

    public string Field4 { get; set; }

    public string NM109_2330 { get; set; }

    public string CLM_11 { get; set; }

    public string ClaimLevelICDErrorFlag { get; set; }

    public string ClaimLevelCLMErrorFlag { get; set; }

    public string HI01 { get; set; }

    public string adjudication_status { get; set; }

}

}
