
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClaimInfo.DataModel
{

using System;
    using System.Collections.Generic;
    
public partial class IntakeClaimLineData
{

    public int SeqID { get; set; }

    public string FileID { get; set; }

    public string ClaimSeqID { get; set; }

    public string TransactionID { get; set; }

    public string FileName { get; set; }

    public string FileDate { get; set; }

    public string BatchID { get; set; }

    public string TransmissionID { get; set; }

    public string ClaimExtNmbr { get; set; }

    public string ClaimID { get; set; }

    public string ClaimTMTrackingID { get; set; }

    public string Subscriber_ID { get; set; }

    public string Member_ID { get; set; }

    public string ExtSubscriber_ID { get; set; }

    public string ICD9ICD10 { get; set; }

    public string ProcNo { get; set; }

    public string DiagnosisXRef { get; set; }

    public string DiagnosisCodes { get; set; }

    public string PatientWeight { get; set; }

    public string Units { get; set; }

    public string UnitMeasure { get; set; }

    public string Proc_Amount { get; set; }

    public string PatientPaid { get; set; }

    public string NetBalance { get; set; }

    public string Adjust { get; set; }

    public string InsuranceBalance { get; set; }

    public string DateofService { get; set; }

    public string DateofServiceEnd { get; set; }

    public string LineStatus { get; set; }

    public string OtherID { get; set; }

    public string ExternalCorrelationToken { get; set; }

    public string AmbulanceInfo { get; set; }

    public string XRayInfo { get; set; }

    public string TransportInfo { get; set; }

    public string ExtraField1 { get; set; }

    public string ExtraField2 { get; set; }

    public string ExtraField3 { get; set; }

    public string ExtraField4 { get; set; }

    public string ExtraField5 { get; set; }

    public string ExtraField6 { get; set; }

    public string ExtraField7 { get; set; }

    public string ExtraField8 { get; set; }

    public string ExtraField9 { get; set; }

    public string CreatedBy { get; set; }

    public string CreateDateTime { get; set; }

    public string Created_Date { get; set; }

    public string HCP01_PricingMethodology { get; set; }

    public string HCP02_Amount { get; set; }

    public string HCP03 { get; set; }

    public string HCP04 { get; set; }

    public string HCP05_Rate { get; set; }

    public string HCP06 { get; set; }

    public string HCP07 { get; set; }

    public string HCP08 { get; set; }

    public string HCP12_Quantity { get; set; }

    public string HCP13 { get; set; }

    public string HCP14 { get; set; }

    public string HCP15_ExceptionCode { get; set; }

    public string AttendingProviderNameLastOrOrganizationName { get; set; }

    public string AttendingProviderNameFirst { get; set; }

    public string NM108_AttendingProvider { get; set; }

    public string NM109_AttendingProvider { get; set; }

    public string AttendingProviderCode { get; set; }

    public string AttendingProvider_PRV02 { get; set; }

    public string AttendingProvider_PRV03 { get; set; }

    public string AttendingProvider_REF01 { get; set; }

    public string AttendingProvider_REF02 { get; set; }

    public string OperatingPhysicianNameLastOrOrganizationName { get; set; }

    public string OperatingPhysicianNameFirst { get; set; }

    public string NM108_OperatingPhysician { get; set; }

    public string NM109_OperatingPhysician { get; set; }

    public string OperatingPhysician_REF01 { get; set; }

    public string OperatingPhysician_REF02 { get; set; }

    public string OtherOperatingPhysicianNameLastOrOrganizationName { get; set; }

    public string OtherOperatingPhysicianNameFirst { get; set; }

    public string NM108_OtherOperatingPhysician { get; set; }

    public string NM109_OtherOperatingPhysician { get; set; }

    public string OtherOperatingPhysician_REF01 { get; set; }

    public string OtherOperatingPhysician_REF02 { get; set; }

    public string RenderingPhysicianNameLastOrOrganizationName { get; set; }

    public string RenderingPhysicianNameFirst { get; set; }

    public string NM108_RenderingPhysician { get; set; }

    public string NM109_RenderingPhysician { get; set; }

    public string RenderingPhysician_REF01 { get; set; }

    public string RenderingPhysician_REF02 { get; set; }

    public string ServiceFacilityLocationName { get; set; }

    public string ServiceFacilityLocation_NM102 { get; set; }

    public string ServiceFacilityLocation_NM108 { get; set; }

    public string ServiceFacilityLocation_NM109 { get; set; }

    public string ServiceFacilityLocationAddress { get; set; }

    public string ServiceFacilityLocation_City_State_Zip { get; set; }

    public string ServiceFacilityLocation_REF01 { get; set; }

    public string ServiceFacilityLocation_REF02 { get; set; }

    public string ReferringProviderNameLastOrOrganizationName { get; set; }

    public string ReferringProviderNameFirst { get; set; }

    public string NM108_ReferringProvider { get; set; }

    public string NM109_ReferringProvider { get; set; }

    public string ReferringProvider_REF01 { get; set; }

    public string ReferringProvider_REF02 { get; set; }

    public string SBR01_PayerResponsibilityCode { get; set; }

    public string SBR02 { get; set; }

    public string SBR03 { get; set; }

    public string SBR04 { get; set; }

    public string SBR09 { get; set; }

    public string CAS01_ClaimAdjustMentGroupCode { get; set; }

    public string CAS02 { get; set; }

    public string CAS03 { get; set; }

    public string CAS04 { get; set; }

    public string CAS05 { get; set; }

    public string CAS06 { get; set; }

    public string CAS07 { get; set; }

    public string CAS08 { get; set; }

    public string CAS09 { get; set; }

    public string CAS10 { get; set; }

    public string CAS11 { get; set; }

    public string CAS12 { get; set; }

    public string CAS13 { get; set; }

    public string CAS14 { get; set; }

    public string CAS15 { get; set; }

    public string CAS16 { get; set; }

    public string CAS17 { get; set; }

    public string CAS18 { get; set; }

    public string CAS19 { get; set; }

    public string AMT01_PayerPaidAmmount { get; set; }

    public string AMT02_Amount { get; set; }

    public string AMT01_RemainingPatientLiability { get; set; }

    public string AMT02_RPAmount { get; set; }

    public string AMT01_NonCoveredChargeAmmount { get; set; }

    public string AMT02_NCAmount { get; set; }

    public string OtherInsuranceCoverage_OI03 { get; set; }

    public string OtherInsuranceCoverage_OI06 { get; set; }

    public string MIA01 { get; set; }

    public string MIA02 { get; set; }

    public string MIA03 { get; set; }

    public string MIA04 { get; set; }

    public string MIA05 { get; set; }

    public string MIA06 { get; set; }

    public string MIA07 { get; set; }

    public string MIA08 { get; set; }

    public string MIA09 { get; set; }

    public string MIA10 { get; set; }

    public string MOA01 { get; set; }

    public string MOA02 { get; set; }

    public string MOA03 { get; set; }

    public string MOA04 { get; set; }

    public string MOA05 { get; set; }

    public string MOA06 { get; set; }

    public string MOA07 { get; set; }

    public string MOA08 { get; set; }

    public string MOA09 { get; set; }

    public string MOA10 { get; set; }

    public string OtherSubscriberNameLastOrOrganizationName { get; set; }

    public string OtherSubscriberNameFirst { get; set; }

    public string OtherSubscriber_NM102 { get; set; }

    public string NM108_OtherSubscriber { get; set; }

    public string NM109_OtherSubscriber { get; set; }

    public string OtherSubscriberAddress { get; set; }

    public string OtherSubscriberCityStateZip { get; set; }

    public string OtherSubscriber_REF01 { get; set; }

    public string OtherSubscriber_RF02 { get; set; }

    public string OtherPayerNameLastOrOrganizationName { get; set; }

    public string OtherPayerNameFirst { get; set; }

    public string OtherPayer_NM102 { get; set; }

    public string NM108_OtherPayer { get; set; }

    public string NM109_OtherPayer { get; set; }

    public string OtherPayerAddress { get; set; }

    public string OtherPayerCityStateZip { get; set; }

    public string ClaimCheckOrRemittanceDate { get; set; }

    public string LX { get; set; }

    public string SV201 { get; set; }

    public string SV202 { get; set; }

    public string SV202_1 { get; set; }

    public string SV202_2 { get; set; }

    public string SV202_3 { get; set; }

    public string SV202_4 { get; set; }

    public string SV202_5 { get; set; }

    public string SV202_6 { get; set; }

    public string SV202_7 { get; set; }

    public string SV203 { get; set; }

    public string SV204 { get; set; }

    public string SV205 { get; set; }

    public string SV207 { get; set; }

    public string LinSupplimentalInfo_PWK01 { get; set; }

    public string PWK02 { get; set; }

    public string PWK05 { get; set; }

    public string ServiceDate { get; set; }

    public string LIN02_DrugIdentification { get; set; }

    public string LIN03 { get; set; }

    public string CTP04_DrugQuantity { get; set; }

    public string CTP05 { get; set; }

    public string CTP05_1 { get; set; }

    public string SVD01 { get; set; }

    public string SVD02 { get; set; }

    public string SVD03 { get; set; }

    public string SVD03_1 { get; set; }

    public string SVD03_2 { get; set; }

    public string SVD03_3 { get; set; }

    public string SVD05 { get; set; }

    public string LineCheckOrRemittanceDate { get; set; }

    public string RemainingPatientLiability { get; set; }

    public string ErrorCode { get; set; }

    public string ClaimLineLevelErrors { get; set; }

    public string Field1 { get; set; }

    public string Field2 { get; set; }

    public string Field3 { get; set; }

    public string Field4 { get; set; }

    public string adjustment { get; set; }

    public string type_of_adjustment { get; set; }

    public string RemainigAmt { get; set; }

}

}
