
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClaimInfo.DataModel
{

using System;
    using System.Collections.Generic;
    
public partial class LCD_Covered_Original
{

    public decimal SeqId { get; set; }

    public string CPT_HCPCS { get; set; }

    public string Exclusion_Type { get; set; }

    public string ICD_Code_Range_Start { get; set; }

    public string ICD_Code_Range_End { get; set; }

    public string Policy_Rule_Summary_or_Reference { get; set; }

    public string ABN_Form_Reason { get; set; }

    public string ABN_Spanish_Form_Reason { get; set; }

    public string Code_Effective_Date { get; set; }

    public string Code_Termination_Date { get; set; }

    public string Frequency_Limit { get; set; }

    public string Frequency_Procedure_Limit { get; set; }

    public string Frequency_Time_Span_Unit { get; set; }

    public string Frequency_Time_Span_Number { get; set; }

    public string Sex { get; set; }

    public string Age_Minimum { get; set; }

    public string Age_Maximum { get; set; }

    public string Age_Unit { get; set; }

    public string Policy_Rule_Key { get; set; }

    public string Policy_Rule_NameorDescriptor { get; set; }

    public string Diagnosis_Group_Identifier { get; set; }

    public string Diagnosis_Group_Logic { get; set; }

    public string Diagnosis_Coding_Order { get; set; }

    public string ExtraField1 { get; set; }

}

}
