
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClaimInfo.DataModel
{

using System;
    using System.Collections.Generic;
    
public partial class MemberCoverageInfo_M1
{

    public int SeqID { get; set; }

    public Nullable<int> FileID { get; set; }

    public string FileName { get; set; }

    public string FullFile { get; set; }

    public Nullable<System.DateTime> LoadMonth { get; set; }

    public Nullable<int> TransactionID { get; set; }

    public string OtherID { get; set; }

    public string SubscriberNo { get; set; }

    public string MEDSID { get; set; }

    public string TransCode { get; set; }

    public string InsLineCode { get; set; }

    public string PlanCoverageDesc { get; set; }

    public string StartDate { get; set; }

    public string EndDate { get; set; }

    public string MemberAmount { get; set; }

    public string Ref171 { get; set; }

    public string Ref9V1 { get; set; }

    public string RefCE1 { get; set; }

    public string RefE81 { get; set; }

    public string RefRB1 { get; set; }

    public string RefXX11 { get; set; }

    public string RefZX1 { get; set; }

    public string RefZZ1 { get; set; }

    public string ReconcileInfo { get; set; }

    public Nullable<int> Reconcile { get; set; }

    public string CreateDateTime { get; set; }

}

}
