
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClaimInfo.DataModel
{

using System;
    using System.Collections.Generic;
    
public partial class MemberInfo_M1
{

    public int SeqID { get; set; }

    public Nullable<int> FileID { get; set; }

    public Nullable<int> TransactionID { get; set; }

    public string FileName { get; set; }

    public string FullFile { get; set; }

    public Nullable<System.DateTime> LoadMonth { get; set; }

    public string OtherID { get; set; }

    public string SubscriberNo { get; set; }

    public string MEDSID { get; set; }

    public string MemberFName { get; set; }

    public string MemberLName { get; set; }

    public string MemberMI { get; set; }

    public string Telephone { get; set; }

    public string StreetAddress { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string PostalCode { get; set; }

    public string County { get; set; }

    public string CountyRes { get; set; }

    public string Race { get; set; }

    public string Ethinicity { get; set; }

    public string Language { get; set; }

    public string FAMELanguge { get; set; }

    public string MailingStreetAddress { get; set; }

    public string MailingCity { get; set; }

    public string MailingState { get; set; }

    public string MailingPostalCode { get; set; }

    public string Ref171 { get; set; }

    public string Ref231 { get; set; }

    public string Ref3H1 { get; set; }

    public string Ref601 { get; set; }

    public string RefDX1 { get; set; }

    public string RefF61 { get; set; }

    public string RefQ41 { get; set; }

    public string RefQQ1 { get; set; }

    public string RefABB1 { get; set; }

    public string RefZZ1 { get; set; }

    public string Status1 { get; set; }

    public string Status2 { get; set; }

    public string ExtraField1 { get; set; }

    public string ExtraField2 { get; set; }

    public string ReconcileInfo { get; set; }

    public Nullable<int> Reconcile { get; set; }

    public string CreateDateTime { get; set; }

    public Nullable<System.DateTime> dob { get; set; }

    public string Gender { get; set; }

    public string error_desc { get; set; }

}

}
